### YamlMime:ManagedReference
items:
- uid: System.ExecutionEngineException
  id: ExecutionEngineException
  children:
  - System.ExecutionEngineException.#ctor
  - System.ExecutionEngineException.#ctor(System.String)
  - System.ExecutionEngineException.#ctor(System.String,System.Exception)
  langs:
  - csharp
  name: ExecutionEngineException
  nameWithType: ExecutionEngineException
  fullName: System.ExecutionEngineException
  type: Class
  summary: "A exceção que é lançada quando há um erro interno no mecanismo de execução do common language runtime. Essa classe não pode ser herdada."
  remarks: "Não há nenhuma alternativa não obsoleta para ExecutionEngineException. Se ainda mais a execução do seu aplicativo não pode ser mantida, use o <xref:System.Environment.FailFast%2A>método.</xref:System.Environment.FailFast%2A>"
  syntax:
    content: >-
      [System.Obsolete("This type previously indicated an unspecified fatal error in the runtime. The runtime no longer raises this exception so this type is obsolete.")]

      [System.Runtime.InteropServices.ComVisible(true)]

      public sealed class ExecutionEngineException : SystemException
  inheritance:
  - System.Exception
  - System.SystemException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.ExecutionEngineException.#ctor
  id: '#ctor'
  parent: System.ExecutionEngineException
  langs:
  - csharp
  name: ExecutionEngineException()
  nameWithType: ExecutionEngineException.ExecutionEngineException()
  fullName: System.ExecutionEngineException.ExecutionEngineException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ExecutionEngineException&quot;> </xref> classe."
  remarks: "Este construtor inicializa a <xref:System.Exception.Message%2A>propriedade da nova instância para uma mensagem fornecida pelo sistema que descreve o erro, como &quot;Erro interno.&quot;</xref:System.Exception.Message%2A> Esta mensagem leva em conta a cultura atual do sistema.       A tabela a seguir mostra os valores de propriedade inicial para uma instância de <xref:System.ExecutionEngineException>.</xref:System.ExecutionEngineException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Uma referência nula (`Nothing` no Visual Basic). |   | <xref:System.Exception.Message%2A>| A cadeia de caracteres de mensagem de erro localizada. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ExecutionEngineException ();
    parameters: []
  overload: System.ExecutionEngineException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ExecutionEngineException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.ExecutionEngineException
  langs:
  - csharp
  name: ExecutionEngineException(String)
  nameWithType: ExecutionEngineException.ExecutionEngineException(String)
  fullName: System.ExecutionEngineException.ExecutionEngineException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ExecutionEngineException&quot;> </xref> classe com uma mensagem de erro especificada."
  remarks: "Este construtor inicializa o <xref:System.Exception.Message%2A?displayProperty=fullName>propriedade da nova exceção usando o `message` parâmetro.</xref:System.Exception.Message%2A?displayProperty=fullName> O conteúdo de `message` se destina a ser compreendidos por humanos. O chamador desse construtor é necessário para garantir que essa cadeia de caracteres foi localizada para a cultura atual do sistema.       A tabela a seguir mostra os valores de propriedade inicial para uma instância de <xref:System.ExecutionEngineException>.</xref:System.ExecutionEngineException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Uma referência nula (`Nothing` no Visual Basic). |   | <xref:System.Exception.Message%2A>| A cadeia de caracteres de mensagem de erro. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ExecutionEngineException (string message);
    parameters:
    - id: message
      type: System.String
      description: "A mensagem que descreve o erro."
  overload: System.ExecutionEngineException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.ExecutionEngineException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.ExecutionEngineException
  langs:
  - csharp
  name: ExecutionEngineException(String,Exception)
  nameWithType: ExecutionEngineException.ExecutionEngineException(String,Exception)
  fullName: System.ExecutionEngineException.ExecutionEngineException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.ExecutionEngineException&quot;> </xref> classe com uma mensagem de erro especificada e uma referência à exceção interna que é a causa dessa exceção."
  remarks: "Uma exceção que é lançada como um resultado direto de uma exceção anterior deve incluir uma referência à exceção anterior no <xref:System.Exception.InnerException%2A>propriedade.</xref:System.Exception.InnerException%2A> O <xref:System.Exception.InnerException%2A>propriedade retorna o mesmo valor que é passado para o construtor, ou uma referência nula (`Nothing` no Visual Basic) se o <xref:System.Exception.InnerException%2A>propriedade não fornecer o valor da exceção interna para o construtor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       A tabela a seguir mostra os valores de propriedade inicial para uma instância de <xref:System.ExecutionEngineException>.</xref:System.ExecutionEngineException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| A referência à exceção interna. |   | <xref:System.Exception.Message%2A>| A cadeia de caracteres de mensagem de erro. |</xref:System.Exception.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public ExecutionEngineException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A mensagem de erro que explica o motivo da exceção."
    - id: innerException
      type: System.Exception
      description: "A exceção que é a causa da exceção atual. Se o `innerException` parâmetro não é uma referência nula (<xref uid=&quot;langword_csharp_Nothing&quot; name=&quot;Nothing&quot; href=&quot;&quot;> </xref> no Visual Basic), a exceção atual é gerada em um <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> bloco que manipula a exceção interna."
  overload: System.ExecutionEngineException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.SystemException
  isExternal: false
  name: System.SystemException
- uid: System.ExecutionEngineException.#ctor
  parent: System.ExecutionEngineException
  isExternal: false
  name: ExecutionEngineException()
  nameWithType: ExecutionEngineException.ExecutionEngineException()
  fullName: System.ExecutionEngineException.ExecutionEngineException()
- uid: System.ExecutionEngineException.#ctor(System.String)
  parent: System.ExecutionEngineException
  isExternal: false
  name: ExecutionEngineException(String)
  nameWithType: ExecutionEngineException.ExecutionEngineException(String)
  fullName: System.ExecutionEngineException.ExecutionEngineException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.ExecutionEngineException.#ctor(System.String,System.Exception)
  parent: System.ExecutionEngineException
  isExternal: false
  name: ExecutionEngineException(String,Exception)
  nameWithType: ExecutionEngineException.ExecutionEngineException(String,Exception)
  fullName: System.ExecutionEngineException.ExecutionEngineException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.ExecutionEngineException.#ctor*
  parent: System.ExecutionEngineException
  isExternal: false
  name: ExecutionEngineException
  nameWithType: ExecutionEngineException.ExecutionEngineException
