### YamlMime:ManagedReference
items:
- uid: System.DuplicateWaitObjectException
  id: DuplicateWaitObjectException
  children:
  - System.DuplicateWaitObjectException.#ctor
  - System.DuplicateWaitObjectException.#ctor(System.String)
  - System.DuplicateWaitObjectException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  - System.DuplicateWaitObjectException.#ctor(System.String,System.Exception)
  - System.DuplicateWaitObjectException.#ctor(System.String,System.String)
  langs:
  - csharp
  name: DuplicateWaitObjectException
  nameWithType: DuplicateWaitObjectException
  fullName: System.DuplicateWaitObjectException
  type: Class
  summary: "A exceção que é lançada quando um objeto aparece mais de uma vez em uma matriz de objetos de sincronização."
  remarks: "O common language runtime fornece um mecanismo de sincronização de thread com base em objetos de sincronização aguardando execução em uma matriz de <xref:System.Threading.WaitHandle>objetos.</xref:System.Threading.WaitHandle> Se a matriz de <xref:System.Threading.WaitHandle>objetos passados para <xref:System.Threading.WaitHandle.WaitAll%2A>ou <xref:System.Threading.WaitHandle.WaitAny%2A>contém qualquer sistema operacional duplicados identificadores, DuplicateWaitObjectException é gerada.</xref:System.Threading.WaitHandle.WaitAny%2A> </xref:System.Threading.WaitHandle.WaitAll%2A> </xref:System.Threading.WaitHandle> Para obter mais informações, consulte <xref:System.Threading.WaitHandle>.</xref:System.Threading.WaitHandle>       DuplicateWaitObjectException usa o HRESULT COR_E_DUPLICATEWAITOBJECT, que tem o valor 0x80131529.       Para obter uma lista de valores de propriedade inicial para uma instância de DuplicateWaitObjectException, consulte o <xref:System.DuplicateWaitObjectException.%23ctor%2A>construtores.</xref:System.DuplicateWaitObjectException.%23ctor%2A>      > [!NOTE] > Esta exceção não está incluída no [.NET para aplicativos Windows Store](http://go.microsoft.com/fwlink/?LinkID=247912) ou o, mas ele é lançado por alguns membros que são. Para capturar a exceção nesse caso, escreva uma `catch` instrução para <xref:System.ArgumentException>em vez disso.</xref:System.ArgumentException>"
  syntax:
    content: >-
      [System.Runtime.InteropServices.ComVisible(true)]

      public class DuplicateWaitObjectException : ArgumentException
  inheritance:
  - System.ArgumentException
  implements: []
  inheritedMembers: []
  platform:
  - net462
- uid: System.DuplicateWaitObjectException.#ctor
  id: '#ctor'
  parent: System.DuplicateWaitObjectException
  langs:
  - csharp
  name: DuplicateWaitObjectException()
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException()
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException()
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.DuplicateWaitObjectException&quot;> </xref> classe."
  remarks: "Este construtor inicializa a <xref:System.Exception.Message%2A>propriedade da nova instância para uma mensagem fornecida pelo sistema que descreve o erro, como &quot;Objetos duplicados no argumento&quot;.</xref:System.Exception.Message%2A> Esta mensagem leva em conta a cultura atual do sistema.       A tabela a seguir mostra os valores de propriedade inicial para uma instância de <xref:System.DuplicateWaitObjectException>.</xref:System.DuplicateWaitObjectException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Uma referência nula (`Nothing` no Visual Basic). |   | <xref:System.ArgumentException.Message%2A>| A cadeia de caracteres de mensagem de erro localizada. |</xref:System.ArgumentException.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DuplicateWaitObjectException ();
    parameters: []
  overload: System.DuplicateWaitObjectException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.DuplicateWaitObjectException.#ctor(System.String)
  id: '#ctor(System.String)'
  parent: System.DuplicateWaitObjectException
  langs:
  - csharp
  name: DuplicateWaitObjectException(String)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(String)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.DuplicateWaitObjectException&quot;> </xref> classe com o nome do parâmetro que faz com que essa exceção."
  remarks: "O conteúdo de `parameterName` se destina a ser compreendidos por humanos.       A tabela a seguir mostra os valores de propriedade inicial para uma instância de <xref:System.DuplicateWaitObjectException>.</xref:System.DuplicateWaitObjectException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Uma referência nula (`Nothing` no Visual Basic). |   | <xref:System.ArgumentException.Message%2A>| A cadeia de caracteres de mensagem de erro localizada. |   | <xref:System.ArgumentException.ParamName%2A>| A cadeia de caracteres de nome de parâmetro. |</xref:System.ArgumentException.ParamName%2A> </xref:System.ArgumentException.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DuplicateWaitObjectException (string parameterName);
    parameters:
    - id: parameterName
      type: System.String
      description: "O nome do parâmetro que causou a exceção."
  overload: System.DuplicateWaitObjectException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.DuplicateWaitObjectException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  id: '#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)'
  parent: System.DuplicateWaitObjectException
  langs:
  - csharp
  name: DuplicateWaitObjectException(SerializationInfo,StreamingContext)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(SerializationInfo,StreamingContext)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(SerializationInfo,StreamingContext)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.DuplicateWaitObjectException&quot;> </xref> classe com os dados serializados."
  remarks: "Este construtor é chamado durante a desserialização para reconstituir o objeto de exceção transmitido em um fluxo. Para obter mais informações, consulte [XML e serialização SOAP](~/add/includes/ajax-current-ext-md.md)."
  syntax:
    content: protected DuplicateWaitObjectException (System.Runtime.Serialization.SerializationInfo info, System.Runtime.Serialization.StreamingContext context);
    parameters:
    - id: info
      type: System.Runtime.Serialization.SerializationInfo
      description: "O objeto que contém os dados do objeto serializado."
    - id: context
      type: System.Runtime.Serialization.StreamingContext
      description: "As informações contextuais sobre a origem ou destino."
  overload: System.DuplicateWaitObjectException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.DuplicateWaitObjectException.#ctor(System.String,System.Exception)
  id: '#ctor(System.String,System.Exception)'
  parent: System.DuplicateWaitObjectException
  langs:
  - csharp
  name: DuplicateWaitObjectException(String,Exception)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(String,Exception)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(String,Exception)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.DuplicateWaitObjectException&quot;> </xref> classe com uma mensagem de erro especificada e uma referência à exceção interna que é a causa dessa exceção."
  remarks: "Uma exceção que é lançada como um resultado direto de uma exceção anterior deve incluir uma referência à exceção anterior no <xref:System.Exception.InnerException%2A>propriedade.</xref:System.Exception.InnerException%2A> O <xref:System.Exception.InnerException%2A>propriedade retorna o mesmo valor que é transmitido a este construtor.</xref:System.Exception.InnerException%2A>       A tabela a seguir mostra os valores de propriedade inicial para uma instância de <xref:System.DuplicateWaitObjectException>.</xref:System.DuplicateWaitObjectException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| A exceção especificada pelo `innerException`. |   | <xref:System.ArgumentException.Message%2A>| A cadeia de caracteres de mensagem de erro especificada pelo `message`. |</xref:System.ArgumentException.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DuplicateWaitObjectException (string message, Exception innerException);
    parameters:
    - id: message
      type: System.String
      description: "A mensagem de erro que explica o motivo da exceção."
    - id: innerException
      type: System.Exception
      description: "A exceção que é a causa da exceção atual. Se o `innerException` parâmetro não é <xref uid=&quot;langword_csharp_null&quot; name=&quot;null&quot; href=&quot;&quot;> </xref>, a exceção atual é gerada em um <xref uid=&quot;langword_csharp_catch&quot; name=&quot;catch&quot; href=&quot;&quot;> </xref> bloco que manipula a exceção interna."
  overload: System.DuplicateWaitObjectException.#ctor*
  exceptions: []
  platform:
  - net462
- uid: System.DuplicateWaitObjectException.#ctor(System.String,System.String)
  id: '#ctor(System.String,System.String)'
  parent: System.DuplicateWaitObjectException
  langs:
  - csharp
  name: DuplicateWaitObjectException(String,String)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(String,String)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(String,String)
  type: Constructor
  assemblies:
  - mscorlib
  namespace: System
  summary: "Inicializa uma nova instância do <xref href=&quot;System.DuplicateWaitObjectException&quot;> </xref> classe com uma mensagem de erro especificada e o nome do parâmetro que faz com que essa exceção."
  remarks: "O conteúdo a `parameterName` e `message` parâmetros se destina a ser compreendidos por humanos. O chamador desse construtor é necessário para garantir que essas cadeias de caracteres foram localizadas para a cultura atual do sistema.       Uma exceção que é lançada como um resultado direto de uma exceção anterior deve incluir uma referência à exceção anterior no <xref:System.Exception.InnerException%2A>propriedade.</xref:System.Exception.InnerException%2A> O <xref:System.Exception.InnerException%2A>propriedade retorna o mesmo valor que é passado para o construtor, ou uma referência nula (`Nothing` no Visual Basic) se o <xref:System.Exception.InnerException%2A>propriedade não fornecer o valor da exceção interna para o construtor.</xref:System.Exception.InnerException%2A> </xref:System.Exception.InnerException%2A>       A tabela a seguir mostra os valores de propriedade inicial para uma instância de <xref:System.DuplicateWaitObjectException>.</xref:System.DuplicateWaitObjectException>      | Propriedade | Valor |   |--------------|-----------|   | <xref:System.Exception.InnerException%2A>| Uma referência nula (`Nothing` no Visual Basic) |   | <xref:System.ArgumentException.Message%2A>| A cadeia de caracteres de mensagem de erro. |   | <xref:System.ArgumentException.ParamName%2A>| A cadeia de caracteres de nome de parâmetro. |</xref:System.ArgumentException.ParamName%2A> </xref:System.ArgumentException.Message%2A> </xref:System.Exception.InnerException%2A>"
  syntax:
    content: public DuplicateWaitObjectException (string parameterName, string message);
    parameters:
    - id: parameterName
      type: System.String
      description: "O nome do parâmetro que causou a exceção."
    - id: message
      type: System.String
      description: "A mensagem que descreve o erro."
  overload: System.DuplicateWaitObjectException.#ctor*
  exceptions: []
  platform:
  - net462
references:
- uid: System.ArgumentException
  isExternal: false
  name: System.ArgumentException
- uid: System.DuplicateWaitObjectException.#ctor
  parent: System.DuplicateWaitObjectException
  isExternal: false
  name: DuplicateWaitObjectException()
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException()
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException()
- uid: System.DuplicateWaitObjectException.#ctor(System.String)
  parent: System.DuplicateWaitObjectException
  isExternal: false
  name: DuplicateWaitObjectException(String)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(String)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(String)
- uid: System.String
  parent: System
  isExternal: true
  name: String
  nameWithType: String
  fullName: System.String
- uid: System.DuplicateWaitObjectException.#ctor(System.Runtime.Serialization.SerializationInfo,System.Runtime.Serialization.StreamingContext)
  parent: System.DuplicateWaitObjectException
  isExternal: false
  name: DuplicateWaitObjectException(SerializationInfo,StreamingContext)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(SerializationInfo,StreamingContext)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(SerializationInfo,StreamingContext)
- uid: System.Runtime.Serialization.SerializationInfo
  parent: System.Runtime.Serialization
  isExternal: false
  name: SerializationInfo
  nameWithType: SerializationInfo
  fullName: System.Runtime.Serialization.SerializationInfo
- uid: System.Runtime.Serialization.StreamingContext
  parent: System.Runtime.Serialization
  isExternal: true
  name: StreamingContext
  nameWithType: StreamingContext
  fullName: System.Runtime.Serialization.StreamingContext
- uid: System.DuplicateWaitObjectException.#ctor(System.String,System.Exception)
  parent: System.DuplicateWaitObjectException
  isExternal: false
  name: DuplicateWaitObjectException(String,Exception)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(String,Exception)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(String,Exception)
- uid: System.Exception
  parent: System
  isExternal: true
  name: Exception
  nameWithType: Exception
  fullName: System.Exception
- uid: System.DuplicateWaitObjectException.#ctor(System.String,System.String)
  parent: System.DuplicateWaitObjectException
  isExternal: false
  name: DuplicateWaitObjectException(String,String)
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException(String,String)
  fullName: System.DuplicateWaitObjectException.DuplicateWaitObjectException(String,String)
- uid: System.DuplicateWaitObjectException.#ctor*
  parent: System.DuplicateWaitObjectException
  isExternal: false
  name: DuplicateWaitObjectException
  nameWithType: DuplicateWaitObjectException.DuplicateWaitObjectException
